name: elaros
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  fl_chart: ^0.66.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.15.7
  flutter_svg: ^2.0.10+1
  pedometer: ^4.0.1
  http: ^1.2.1
  pdf: ^3.6.0
  path_provider: ^2.0.2
  permission_handler: ^11.3.0
  printing: ^5.6.0
  mailer: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
